### ISSUE TITLE
aws:ecs:serviceName missing

### ISSUE THREAD

**Issue by gregn610** [dethmix/self-healing-zookeeper#2]
Hi, Thanks for the article. 
After triple checking [enable_ecs_managed_tags = true](https://github.com/dethmix/self-healing-zookeeper/blob/master/terraform/ecs-zookeeper.tf#L29) and even switching AMI, I'm still not getting the serviceName tags in another cluster. 
Is there something else it requires ?

```
"aws:ecs:clusterName":"zookeeper"
"aws:ecs:serviceName:"zoo2"
```

cheers,
/g

**Comment by dethmix** [comment]
Hi @gregn610 it looks like your IAM user didn't use "new format of ARN for ECS".
In AWS web console go to ECS -> click Account Settings and check `Amazon ECS ARN and resource ID settings` section. To use ECS service level tags you need to opt-in that new format. 
![image](https://user-images.githubusercontent.com/13799832/91589746-47282b80-e928-11ea-83f5-c74a709abf5b.png)

After that you may want to re-apply your terraform and as a final confirmation that everything is okay check "tags" tag of zookeeper service. It should have 1 tag:
![image](https://user-images.githubusercontent.com/13799832/91589914-7fc80500-e928-11ea-9a7a-e147c4a67391.png)

Now tag should be accessible via metadata.
